server:
  port: 8888

spring:
  application:
    name: crm-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenjian122/config-server.git
        force-pull: true

